import type { LowcodeTemplateResource } from "@meumall/lowcode-adapters";
import { createLowcodePageSchema } from "@meumall/lowcode-schema";

export type PageTemplate = LowcodeTemplateResource;

const productItems = [
  {
    id: "sku_001",
    title: "轻盈通勤手提包",
    priceText: "¥199",
    originPriceText: "¥299",
    desc: "活动价",
    imageUrl: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "sku_002",
    title: "夏季舒适凉鞋",
    priceText: "¥129",
    originPriceText: "¥199",
    desc: "限时补贴",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "sku_003",
    title: "防晒轻薄衬衫",
    priceText: "¥159",
    originPriceText: "¥239",
    desc: "热卖单品",
    imageUrl: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=300&q=80",
  },
];

const storeExpertItems = [
  {
    id: "store_jingan",
    typeText: "门店",
    title: "MeuMall 上海静安店",
    subtitle: "本周热卖搭配到店试穿",
    metricText: "4.9 分",
    desc: "距你 2.1km",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "expert_summer",
    typeText: "达人",
    title: "小夏的通勤穿搭",
    subtitle: "每日更新包袋和鞋履组合",
    metricText: "12.8w 粉丝",
    desc: "直播中",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
  },
];

export const pageTemplates: PageTemplate[] = [
  {
    id: "summer-campaign",
    title: "大促活动页",
    description: "适合节日促销、平台大促和主题营销。",
    category: "活动营销",
    status: "published",
    tags: ["大促", "节日", "楼层", "优惠券"],
    version: "1.0.0",
    schema: createLowcodePageSchema({
      pageId: "summer-campaign-demo",
      title: "夏日好物节",
      pageType: "activity",
      targetPlatforms: ["h5"],
      layout: {
        safeArea: true,
        backgroundColor: "#f3f4f6",
        maxWidth: 430,
      },
      nodes: [
        {
          id: "summer_hero",
          componentName: "ActivityHero",
          materialVersion: "0.1.0",
          props: {
            title: "夏日好物节",
            subtitle: "精选爆品限时补贴，运营可直接组合物料生成页面。",
            imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80",
            backgroundColor: "#ffffff",
            titleColor: "#111827",
            textColor: "#64748b",
            titleSize: 24,
            imageRadius: 8,
            paddingY: 18,
            titleLineHeight: 1.2,
            subtitleLineHeight: 1.6,
          },
        },
        {
          id: "summer_notice",
          componentName: "NoticeBar",
          materialVersion: "0.1.0",
          props: {
            showIcon: true,
            iconText: "!",
            label: "公告",
            content: "活动期间下单即享限时补贴，库存有限先到先得。",
            backgroundColor: "#fffbeb",
            labelBackgroundColor: "rgba(146, 64, 14, 0.1)",
            labelColor: "#92400e",
            textColor: "#92400e",
            borderColor: "#fde68a",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_rich_text",
          componentName: "RichTextBlock",
          materialVersion: "0.1.0",
          props: {
            html: "<p><strong>活动说明：</strong>页面说明、参与规则和补充文案可以通过富文本块直接配置。</p>",
            backgroundColor: "#ffffff",
            textColor: "#374151",
            borderColor: "#e5e7eb",
            radius: 10,
            padding: 14,
            fontSize: 14,
            lineHeight: 1.7,
          },
        },
        {
          id: "summer_basic_button",
          componentName: "BasicButton",
          materialVersion: "0.1.0",
          props: {
            text: "基础按钮示例",
            variant: "outline",
            size: "md",
            block: true,
            backgroundColor: "#0f766e",
            textColor: "#0f766e",
            borderColor: "#0f766e",
            wrapperBackgroundColor: "#f3f4f6",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_link",
          componentName: "BasicLink",
          materialVersion: "0.1.0",
          props: {
            text: "查看基础链接示例",
            subtitle: "轻量入口适合承载规则、说明、专题或外部链接。",
            prefixText: "链接",
            linkUrl: "/activity/summer-guide",
            targetBlank: false,
            showArrow: true,
            arrowText: "›",
            variant: "bar",
            disabled: false,
            underline: false,
            wrapperBackgroundColor: "#f3f4f6",
            backgroundColor: "#ffffff",
            textColor: "#111827",
            subtitleColor: "#64748b",
            prefixColor: "#0f766e",
            prefixBackgroundColor: "rgba(15, 118, 110, 0.1)",
            arrowColor: "#94a3b8",
            borderColor: "#d1d5db",
            borderWidth: 1,
            radius: 10,
            prefixRadius: 999,
            paddingY: 10,
            padding: 12,
            gap: 10,
            fontSize: 14,
            fontWeight: 800,
            arrowSize: 20,
            shadow: false,
          },
        },
        {
          id: "summer_basic_alert",
          componentName: "BasicAlert",
          materialVersion: "0.1.0",
          props: {
            title: "基础提示示例",
            content: "适合配置页面注意事项、成功反馈、风险提醒或运营说明，不接远程消息中心。",
            badgeText: "说明",
            actionText: "查看说明",
            tone: "warning",
            variant: "soft",
            showIcon: true,
            showAction: true,
            iconText: "!",
            wrapperBackgroundColor: "#f3f4f6",
            backgroundColor: "#fff7ed",
            titleColor: "#9a3412",
            contentColor: "#c2410c",
            accentColor: "#ea580c",
            borderColor: "#fed7aa",
            iconColor: "#ffffff",
            iconBackgroundColor: "#ea580c",
            badgeColor: "#ea580c",
            badgeBackgroundColor: "rgba(255, 255, 255, 0.76)",
            actionBackgroundColor: "#ea580c",
            actionTextColor: "#ffffff",
            borderWidth: 1,
            radius: 12,
            badgeRadius: 999,
            actionRadius: 999,
            paddingY: 10,
            padding: 14,
            gap: 10,
            iconSize: 24,
            titleSize: 15,
            contentSize: 13,
            actionAlign: "left",
            shadow: false,
          },
        },
        {
          id: "summer_basic_input",
          componentName: "BasicInput",
          materialVersion: "0.1.0",
          props: {
            label: "基础输入框示例",
            placeholder: "请输入想看的活动品类",
            helperText: "单行输入框可作为后续表单物料的基础单元。",
            type: "text",
            wrapperBackgroundColor: "#f3f4f6",
            inputBackgroundColor: "#ffffff",
            labelColor: "#111827",
            textColor: "#111827",
            helperColor: "#64748b",
            borderColor: "#d1d5db",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_textarea",
          componentName: "BasicTextarea",
          materialVersion: "0.1.0",
          props: {
            label: "基础多行输入示例",
            placeholder: "请输入活动备注或补充说明",
            helperText: "多行输入可作为备注、需求说明和表单扩展的基础单元。",
            rows: 3,
            wrapperBackgroundColor: "#f3f4f6",
            textareaBackgroundColor: "#ffffff",
            labelColor: "#111827",
            textColor: "#111827",
            helperColor: "#64748b",
            borderColor: "#d1d5db",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_select",
          componentName: "BasicSelect",
          materialVersion: "0.1.0",
          props: {
            label: "基础选择框示例",
            placeholder: "请选择偏好的会场",
            helperText: "静态单选可作为后续表单和筛选物料的基础单元。",
            defaultValue: "",
            options: [
              { label: "女装会场", value: "women" },
              { label: "鞋包配饰", value: "accessories" },
              { label: "直播专场", value: "live" },
            ],
            wrapperBackgroundColor: "#f3f4f6",
            selectBackgroundColor: "#ffffff",
            labelColor: "#111827",
            textColor: "#111827",
            helperColor: "#64748b",
            borderColor: "#d1d5db",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_radio_group",
          componentName: "BasicRadioGroup",
          materialVersion: "0.1.0",
          props: {
            label: "基础单选组示例",
            helperText: "单选组适合少量静态选项直接展示，和下拉选择框互补。",
            defaultValue: "women",
            options: [
              { label: "女装会场", value: "women" },
              { label: "鞋包配饰", value: "accessories" },
              { label: "直播专场", value: "live" },
            ],
            wrapperBackgroundColor: "#f3f4f6",
            optionBackgroundColor: "#ffffff",
            labelColor: "#111827",
            textColor: "#111827",
            helperColor: "#64748b",
            activeColor: "#0f766e",
            borderColor: "#d1d5db",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_stepper",
          componentName: "BasicStepper",
          materialVersion: "0.1.0",
          props: {
            label: "基础步进器示例",
            helperText: "步进器适合业务无关的数字增减选择，业务保存由 action 或表单协议扩展。",
            defaultValue: 2,
            min: 0,
            max: 10,
            step: 1,
            wrapperBackgroundColor: "#f3f4f6",
            buttonBackgroundColor: "#ffffff",
            labelColor: "#111827",
            textColor: "#111827",
            helperColor: "#64748b",
            accentColor: "#0f766e",
            borderColor: "#d1d5db",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_switch",
          componentName: "BasicSwitch",
          materialVersion: "0.1.0",
          props: {
            label: "基础开关示例",
            checkedText: "展示活动提醒",
            uncheckedText: "隐藏活动提醒",
            helperText: "布尔开关可作为后续偏好设置和表单协议的基础单元。",
            defaultChecked: true,
            wrapperBackgroundColor: "#f3f4f6",
            labelColor: "#111827",
            stateTextColor: "#64748b",
            helperColor: "#64748b",
            activeColor: "#0f766e",
            inactiveColor: "#cbd5e1",
            thumbColor: "#ffffff",
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_checkbox",
          componentName: "BasicCheckbox",
          materialVersion: "0.1.0",
          props: {
            label: "基础复选框示例",
            helperText: "复选框适合协议确认、偏好勾选和多选列表的基础单元。",
            defaultChecked: true,
            wrapperBackgroundColor: "#f3f4f6",
            labelColor: "#111827",
            helperColor: "#64748b",
            checkedColor: "#0f766e",
            borderColor: "#cbd5e1",
            markColor: "#ffffff",
            radius: 6,
            paddingY: 10,
          },
        },
        {
          id: "summer_basic_form",
          componentName: "BasicForm",
          materialVersion: "0.1.0",
          props: {
            title: "基础表单示例",
            description: "表单容器可以继续添加基础输入、选择、开关和复选物料，提交时会携带字段值。",
            submitText: "提交表单",
            successText: "已触发表单提交事件",
            emptyText: "向表单中添加输入物料",
            showSuccessMessage: true,
            backgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            titleColor: "#111827",
            descriptionColor: "#64748b",
            buttonColor: "#0f766e",
            buttonTextColor: "#ffffff",
            successColor: "#0f766e",
            borderColor: "#d1d5db",
            borderWidth: 1,
            radius: 12,
            buttonRadius: 10,
            paddingY: 12,
            padding: 12,
            gap: 8,
            shadow: true,
          },
          events: {
            onSubmit: { actionId: "summer_basic_form_submit" },
          },
          children: [
            {
              id: "summer_basic_form_input",
              componentName: "BasicInput",
              materialVersion: "0.1.0",
              props: {
                label: "表单内输入框",
                placeholder: "请输入昵称",
                helperText: "提交表单时会携带当前昵称字段。",
                type: "text",
                defaultValue: "MeuMall 用户",
                wrapperBackgroundColor: "transparent",
                inputBackgroundColor: "#ffffff",
                labelColor: "#111827",
                textColor: "#111827",
                helperColor: "#64748b",
                borderColor: "#d1d5db",
                radius: 8,
                paddingY: 0,
              },
            },
            {
              id: "summer_basic_form_checkbox",
              componentName: "BasicCheckbox",
              materialVersion: "0.1.0",
              props: {
                label: "同意接收活动通知",
                helperText: "提交表单时会携带当前勾选状态。",
                defaultChecked: false,
                wrapperBackgroundColor: "transparent",
                labelColor: "#111827",
                helperColor: "#64748b",
                checkedColor: "#0f766e",
                borderColor: "#cbd5e1",
                markColor: "#ffffff",
                radius: 6,
                paddingY: 0,
              },
            },
          ],
        },
        {
          id: "summer_basic_list",
          componentName: "BasicList",
          materialVersion: "0.1.0",
          props: {
            title: "基础列表示例",
            subtitle: "适合配置活动步骤、权益说明、注意事项或 FAQ 摘要。",
            marker: "number",
            items: [
              {
                id: "list_step_1",
                title: "确认页面主题",
                description: "先明确活动页主视觉、核心文案和转化目标。",
                badgeText: "1",
                metaText: "准备",
              },
              {
                id: "list_step_2",
                title: "配置基础内容",
                description: "用通用物料组合图片、文本、列表、按钮和表单。",
                badgeText: "2",
                metaText: "编辑",
              },
              {
                id: "list_step_3",
                title: "预览并提交发布",
                description: "检查 H5 展示效果和安全 action 绑定后进入发布流程。",
                badgeText: "3",
                metaText: "交付",
              },
            ],
            backgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            itemBackgroundColor: "#ffffff",
            titleColor: "#111827",
            subtitleColor: "#64748b",
            itemTitleColor: "#111827",
            itemDescriptionColor: "#64748b",
            metaColor: "#0f766e",
            markerColor: "#0f766e",
            markerTextColor: "#ffffff",
            borderColor: "#d1d5db",
            itemBorderColor: "#e5e7eb",
            borderWidth: 1,
            radius: 12,
            itemRadius: 10,
            paddingY: 12,
            padding: 12,
            itemPadding: 12,
            gap: 8,
            shadow: true,
          },
        },
        {
          id: "summer_basic_accordion",
          componentName: "BasicAccordion",
          materialVersion: "0.1.0",
          props: {
            title: "基础折叠面板示例",
            subtitle: "用于配置 FAQ、规则说明和注意事项，只做本地展开收起。",
            mode: "multiple",
            icon: "chevron",
            defaultOpenFirst: true,
            defaultOpenIds: [],
            items: [
              {
                id: "accordion_rule_1",
                title: "什么时候适合使用？",
                content: "当页面内容较长，但用户只需要按需查看部分说明时，可以用折叠面板收纳内容。",
                badgeText: "Q1",
              },
              {
                id: "accordion_rule_2",
                title: "是否会请求接口？",
                content: "不会。基础折叠面板只渲染静态配置项，远程 FAQ 或活动规则应由后续数据源协议或业务物料承接。",
                badgeText: "Q2",
              },
              {
                id: "accordion_rule_3",
                title: "点击可以埋点吗？",
                content: "可以绑定 onItemToggle 安全 action，由宿主决定是否记录埋点、联动或持久化状态。",
                badgeText: "Q3",
              },
            ],
            backgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            itemBackgroundColor: "#ffffff",
            titleColor: "#111827",
            subtitleColor: "#64748b",
            itemTitleColor: "#111827",
            contentColor: "#64748b",
            badgeColor: "#0f766e",
            badgeBackgroundColor: "rgba(15, 118, 110, 0.1)",
            iconColor: "#64748b",
            iconBackgroundColor: "transparent",
            borderColor: "#d1d5db",
            itemBorderColor: "#e5e7eb",
            borderWidth: 1,
            radius: 12,
            itemRadius: 10,
            badgeRadius: 999,
            paddingY: 12,
            padding: 12,
            itemPadding: 12,
            gap: 8,
            shadow: true,
          },
        },
        {
          id: "summer_basic_timeline",
          componentName: "BasicTimeline",
          materialVersion: "0.1.0",
          props: {
            title: "基础时间线示例",
            subtitle: "用于配置活动节奏、流程节点或服务步骤，不接远程进度。",
            marker: "number",
            showTime: true,
            showConnector: true,
            items: [
              {
                id: "timeline_prepare",
                title: "准备素材和文案",
                description: "整理主图、说明文案和目标动作。",
                timeText: "第 1 步",
                badgeText: "准备",
                status: "done",
              },
              {
                id: "timeline_build",
                title: "搭建并预览页面",
                description: "用基础物料组合页面，并检查 H5 渲染效果。",
                timeText: "第 2 步",
                badgeText: "编辑",
                status: "active",
              },
              {
                id: "timeline_publish",
                title: "提交发布流程",
                description: "完成发布检查后提交审批或发布。",
                timeText: "第 3 步",
                badgeText: "交付",
                status: "pending",
              },
            ],
            backgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            itemBackgroundColor: "#ffffff",
            titleColor: "#111827",
            subtitleColor: "#64748b",
            itemTitleColor: "#111827",
            itemDescriptionColor: "#64748b",
            timeColor: "#0f766e",
            statusColor: "#0f766e",
            markerColor: "#0f766e",
            markerTextColor: "#ffffff",
            badgeBackgroundColor: "rgba(15, 118, 110, 0.1)",
            lineColor: "#99f6e4",
            borderColor: "#d1d5db",
            itemBorderColor: "#e5e7eb",
            borderWidth: 1,
            lineWidth: 2,
            radius: 12,
            itemRadius: 10,
            markerRadius: 999,
            paddingY: 12,
            padding: 12,
            itemPadding: 12,
            gap: 12,
            shadow: true,
          },
        },
        {
          id: "summer_basic_text",
          componentName: "BasicText",
          materialVersion: "0.1.0",
          props: {
            text: "基础文本示例：用于普通说明、温馨提示和活动辅助文案。",
            as: "p",
            fontSize: 14,
            fontWeight: 500,
            lineHeight: 1.7,
            align: "left",
            color: "#334155",
            backgroundColor: "#f3f4f6",
            paddingY: 8,
          },
        },
        {
          id: "summer_basic_price",
          componentName: "BasicPrice",
          materialVersion: "0.1.0",
          props: {
            amountText: "199",
            prefix: "¥",
            suffix: "起",
            align: "left",
            size: 26,
            color: "#dc2626",
            wrapperBackgroundColor: "#f3f4f6",
            paddingY: 8,
          },
        },
        {
          id: "summer_divider",
          componentName: "DividerBlock",
          materialVersion: "0.1.0",
          props: {
            color: "#cbd5e1",
            thickness: 1,
            lineStyle: "dashed",
            inset: 16,
            paddingY: 8,
            backgroundColor: "#f3f4f6",
          },
        },
        {
          id: "summer_basic_image",
          componentName: "BasicImage",
          materialVersion: "0.1.0",
          props: {
            imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
            alt: "基础图片示例",
            ratio: "16 / 9",
            fit: "cover",
            radius: 10,
            paddingY: 8,
            backgroundColor: "#f3f4f6",
          },
        },
        {
          id: "summer_basic_tag",
          componentName: "BasicTag",
          materialVersion: "0.1.0",
          props: {
            text: "基础标签示例",
            tone: "accent",
            align: "left",
            textColor: "#0f766e",
            backgroundColor: "rgba(15, 118, 110, 0.1)",
            wrapperBackgroundColor: "#f3f4f6",
            radius: 999,
            fontSize: 12,
            fontWeight: 800,
            paddingY: 8,
          },
        },
        {
          id: "summer_basic_card",
          componentName: "BasicCard",
          materialVersion: "0.1.0",
          props: {
            imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
            alt: "基础图文卡片示例",
            ratio: "16 / 9",
            fit: "cover",
            badgeText: "基础图文卡片示例",
            title: "周末轻旅行穿搭",
            description: "把图片、标签、标题、说明和按钮组合成一个通用卡片，适合活动入口和内容推荐。",
            buttonText: "查看搭配",
            showButton: true,
            wrapperBackgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            badgeBackgroundColor: "rgba(15, 118, 110, 0.1)",
            titleColor: "#111827",
            textColor: "#64748b",
            accentColor: "#0f766e",
            buttonTextColor: "#ffffff",
            radius: 12,
            buttonRadius: 999,
            borderColor: "#d1d5db",
            borderWidth: 1,
            shadow: true,
            paddingY: 8,
            contentPadding: 12,
          },
        },
        {
          id: "summer_basic_carousel",
          componentName: "BasicCarousel",
          materialVersion: "0.1.0",
          props: {
            ratio: "16 / 9",
            fit: "cover",
            radius: 12,
            autoPlay: true,
            interval: 3200,
            indicator: "dots",
            wrapperBackgroundColor: "#f3f4f6",
            backgroundColor: "#111827",
            titleColor: "#ffffff",
            textColor: "rgba(255, 255, 255, 0.86)",
            accentColor: "#ffffff",
            indicatorColor: "#0f766e",
            titleSize: 18,
            paddingY: 8,
            shadow: true,
            items: [
              {
                id: "summer_carousel_new",
                title: "夏日新品首发",
                subtitle: "用多张图片承载主视觉、权益和会场入口。",
                badgeText: "NEW",
                imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
                linkUrl: "",
              },
              {
                id: "summer_carousel_coupon",
                title: "限时券包加码",
                subtitle: "标题、说明、角标和点击 action 可统一配置。",
                badgeText: "HOT",
                imageUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
                linkUrl: "",
              },
            ],
          },
        },
        {
          id: "summer_basic_video",
          componentName: "BasicVideo",
          materialVersion: "0.1.0",
          props: {
            videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
            posterUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
            badgeText: "VIDEO",
            title: "夏日穿搭视频",
            description: "视频地址、封面、播放行为和基础样式都由通用物料承载，后续可接入素材中心。",
            ratio: "16 / 9",
            radius: 12,
            controls: true,
            autoPlay: false,
            muted: true,
            loop: false,
            playsInline: true,
            wrapperBackgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            mediaBackgroundColor: "#0f172a",
            badgeBackgroundColor: "rgba(15, 118, 110, 0.1)",
            titleColor: "#111827",
            textColor: "#64748b",
            accentColor: "#0f766e",
            borderColor: "#d1d5db",
            titleSize: 18,
            paddingY: 8,
            contentPadding: 12,
            shadow: true,
          },
        },
        {
          id: "summer_basic_modal",
          componentName: "BasicModal",
          materialVersion: "0.1.0",
          props: {
            triggerText: "查看基础弹窗",
            summary: "通用弹窗适合承载静态说明、运营提示和活动引导。",
            modalTitle: "基础弹窗示例",
            content: "这是一个业务无关的基础弹窗物料。\\n它复用 runtime primitives，不请求业务接口，后续可作为权益说明、操作提示或页面引导的基础组件。",
            primaryText: "我知道了",
            closeLabel: "关闭基础弹窗",
            defaultOpen: false,
            closeOnBackdrop: true,
            placement: "bottom",
            backgroundColor: "#f3f4f6",
            modalBackgroundColor: "#ffffff",
            textColor: "#111827",
            helperColor: "#64748b",
            contentColor: "#374151",
            buttonColor: "#0f766e",
            buttonTextColor: "#ffffff",
            radius: 16,
            paddingY: 8,
            contentPadding: 16,
          },
        },
        {
          id: "summer_rules",
          componentName: "ActivityRuleModal",
          materialVersion: "0.1.0",
          props: {
            title: "活动规则",
            summary: "查看补贴时间、参与条件和优惠说明。",
            buttonText: "查看规则",
            modalTitle: "夏日好物节规则",
            primaryColor: "#111827",
            backgroundColor: "#ffffff",
            textColor: "#374151",
            rules: [
              { title: "活动时间", content: "2026-07-31 10:00 至 2026-08-07 23:59。" },
              { title: "参与条件", content: "活动商品数量有限，同一用户限享一次平台补贴。" },
              { title: "优惠说明", content: "优惠不可叠加，最终以结算页展示金额为准。" },
            ],
          },
        },
        {
          id: "summer_countdown",
          componentName: "CountdownTimer",
          materialVersion: "0.1.0",
          props: {
            title: "大促限时抢",
            subtitle: "距离本轮活动结束",
            days: "00",
            hours: "08",
            minutes: "30",
            seconds: "00",
            backgroundColor: "#dc2626",
            textColor: "#ffffff",
            numberColor: "#dc2626",
          },
        },
        {
          id: "summer_live",
          componentName: "LiveEntry",
          materialVersion: "0.1.0",
          props: {
            title: "今晚 8 点直播专场",
            subtitle: "主播讲解夏日搭配和爆品清单，直播间同步发放限时券。",
            statusText: "直播中",
            viewerText: "12.8w 人正在看",
            buttonText: "进入直播",
            coverImageUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=300&q=80",
            linkUrl: "",
            backgroundColor: "#111827",
            titleColor: "#ffffff",
            textColor: "#d1d5db",
            accentColor: "#ef4444",
          },
        },
        {
          id: "summer_floor_anchor",
          componentName: "FloorAnchorNav",
          materialVersion: "0.1.0",
          props: {
            title: "",
            sticky: true,
            smooth: true,
            offsetTop: 0,
            radius: 999,
            backgroundColor: "#ffffff",
            itemBackgroundColor: "#f3f4f6",
            textColor: "#111827",
            items: [
              { id: "anchor_coupon", title: "领券", targetId: "summer_coupon" },
              { id: "anchor_live", title: "直播", targetId: "summer_live" },
              { id: "anchor_brand", title: "品牌", targetId: "summer_brand" },
              { id: "anchor_rank", title: "榜单", targetId: "summer_rank" },
              { id: "anchor_recommend", title: "推荐", targetId: "summer_store_expert" },
              { id: "anchor_pick", title: "精选专区", targetId: "summer_container" },
              { id: "anchor_flash", title: "限时秒杀", targetId: "summer_flash_sale" },
            ],
          },
        },
        {
          id: "summer_nav",
          componentName: "NavGrid",
          materialVersion: "0.1.0",
          props: {
            columns: 4,
            backgroundColor: "#ffffff",
            itemBackgroundColor: "#f8fafc",
            textColor: "#111827",
            radius: 8,
            items: [
              { id: "nav_coupon", title: "领券", subtitle: "新人礼" },
              { id: "nav_flash", title: "秒杀", subtitle: "限时抢" },
              { id: "nav_store", title: "门店", subtitle: "附近热推" },
              { id: "nav_bag", title: "包袋", subtitle: "精选" },
            ],
          },
        },
        {
          id: "summer_section_title_pick",
          componentName: "SectionTitle",
          materialVersion: "0.1.0",
          props: {
            markerText: "今日主推",
            title: "先领券，再逛精选好物",
            subtitle: "用清晰楼层标题把优惠、品牌、榜单和推荐模块串起来。",
            align: "left",
            backgroundColor: "#f3f4f6",
            titleColor: "#111827",
            textColor: "#64748b",
            accentColor: "#0f766e",
            titleSize: 20,
            paddingY: 18,
          },
        },
        {
          id: "summer_image_card_grid",
          componentName: "ImageCardGrid",
          materialVersion: "0.1.0",
          props: {
            title: "专题会场",
            subtitle: "按场景快速进入对应分会场，减少用户选择成本。",
            columns: 2,
            gap: 10,
            radius: 10,
            backgroundColor: "#f3f4f6",
            cardBackgroundColor: "#111827",
            titleColor: "#111827",
            textColor: "#64748b",
            accentColor: "#ef4444",
            items: [
              {
                id: "women",
                title: "女装会场",
                subtitle: "夏日通勤穿搭",
                badgeText: "热推",
                imageUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=500&q=80",
                linkUrl: "",
              },
              {
                id: "shoes",
                title: "鞋包会场",
                subtitle: "轻盈出行装备",
                badgeText: "新品",
                imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=500&q=80",
                linkUrl: "",
              },
            ],
          },
        },
        {
          id: "summer_tabs_block",
          componentName: "TabsBlock",
          materialVersion: "0.1.0",
          props: {
            title: "活动信息",
            subtitle: "把活动亮点、参与方式和常见问题收纳在一个通用内容区块。",
            backgroundColor: "#f3f4f6",
            cardBackgroundColor: "#ffffff",
            navBackgroundColor: "#f8fafc",
            tabBackgroundColor: "#ffffff",
            titleColor: "#111827",
            textColor: "#64748b",
            contentColor: "#374151",
            activeTextColor: "#ffffff",
            accentColor: "#111827",
            borderColor: "#e5e7eb",
            radius: 12,
            paddingY: 14,
            items: [
              {
                id: "highlight",
                title: "活动亮点",
                subtitle: "本期主推",
                badgeText: "Hot",
                content: "精选爆品、组合券包、品牌专题和门店达人内容都可在本页完成搭建。",
              },
              {
                id: "guide",
                title: "参与方式",
                subtitle: "三步完成",
                badgeText: "",
                content: "先领取优惠券，再进入专题会场，最后选择商品或门店内容完成转化。",
              },
              {
                id: "faq",
                title: "常见问题",
                subtitle: "运营说明",
                badgeText: "FAQ",
                content: "活动时间、优惠门槛和售后规则可在这里统一说明，减少用户跳出。",
              },
            ],
          },
        },
        {
          id: "summer_coupon",
          componentName: "CouponSection",
          materialVersion: "0.1.0",
          props: {
            title: "新人专享券",
            buttonText: "立即领取",
            backgroundColor: "#fff7ed",
            buttonColor: "#111827",
          },
        },
        {
          id: "summer_coupon_bundle",
          componentName: "CouponBundle",
          materialVersion: "0.1.0",
          props: {
            title: "大促组合券",
            subtitle: "平台券、品类券一次领，凑单更划算。",
            receiveAllText: "一键领取",
            receiveText: "领取",
            backgroundColor: "#fff7ed",
            titleColor: "#9a3412",
            amountColor: "#dc2626",
            buttonColor: "#ea580c",
            coupons: [
              { id: "coupon_platform_30", title: "满 199 减 30", thresholdText: "平台通用券", valueText: "¥30", expireText: "领取后 7 天有效" },
              { id: "coupon_category_80", title: "满 399 减 80", thresholdText: "包袋鞋履可用", valueText: "¥80", expireText: "每日限量" },
              { id: "coupon_shipping", title: "满 99 包邮", thresholdText: "指定区域可用", valueText: "包邮", expireText: "活动期内有效" },
            ],
          },
        },
        {
          id: "summer_brand",
          componentName: "BrandFeatureSection",
          materialVersion: "0.1.0",
          props: {
            brandName: "MeuMall Select",
            title: "夏日品牌馆",
            description: "精选品牌当季新品与平台补贴权益，帮助用户快速进入品牌导购场景。",
            badgeText: "品牌专题",
            buttonText: "进入品牌",
            coverImageUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80",
            logoImageUrl: "",
            linkUrl: "",
            backgroundColor: "#f8fafc",
            cardBackgroundColor: "#ffffff",
            pointBackgroundColor: "#f8fafc",
            titleColor: "#111827",
            textColor: "#374151",
            accentColor: "#111827",
            sellingPoints: [
              { id: "point_member", title: "会员专享", desc: "品牌券叠加平台补贴" },
              { id: "point_new", title: "当季新品", desc: "通勤、度假和日常穿搭一次配齐" },
            ],
            items: productItems.slice(0, 2),
          },
          dataBinding: {
            items: "products",
          },
        },
        {
          id: "summer_rank",
          componentName: "ProductRankList",
          materialVersion: "0.1.0",
          props: {
            title: "夏日热卖榜",
            subtitle: "按活动热度整理，帮助用户快速选爆品。",
            badgeText: "热卖榜",
            buttonText: "去看看",
            backgroundColor: "#ffffff",
            titleColor: "#111827",
            accentColor: "#ef4444",
            rankBackgroundColor: "#fff1f2",
            limit: 3,
            items: productItems,
          },
          dataBinding: {
            items: "products",
          },
        },
        {
          id: "summer_store_expert",
          componentName: "StoreExpertSection",
          materialVersion: "0.1.0",
          props: {
            title: "门店/达人推荐",
            subtitle: "附近门店和热门达人帮你快速选好物。",
            badgeText: "本地热推",
            buttonText: "查看",
            backgroundColor: "#f8fafc",
            cardBackgroundColor: "#ffffff",
            titleColor: "#111827",
            accentColor: "#0f766e",
            items: storeExpertItems,
          },
        },
        {
          id: "summer_container",
          componentName: "SectionContainer",
          materialVersion: "0.1.0",
          props: {
            title: "精选专区",
            subtitle: "容器中可以继续添加物料。",
            backgroundColor: "#ffffff",
            padding: 14,
            marginY: 12,
            gap: 10,
            radius: 12,
            borderColor: "#d1d5db",
            borderWidth: 1,
            shadow: true,
            titleColor: "#111827",
            subtitleColor: "#64748b",
            emptyText: "向精选专区中添加物料",
          },
          children: [
            {
              id: "summer_action",
              componentName: "ActionButton",
              materialVersion: "0.1.0",
              props: {
                text: "立即逛精选",
                linkUrl: "",
                backgroundColor: "#111827",
                textColor: "#ffffff",
                wrapperBackgroundColor: "#ffffff",
                radius: 8,
                paddingY: 8,
              },
            },
            {
              id: "summer_banner",
              componentName: "ImageBanner",
              materialVersion: "0.1.0",
              props: {
                imageUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80",
                alt: "",
                radius: 8,
              },
            },
          ],
        },
        {
          id: "summer_grid_container",
          componentName: "GridContainer",
          materialVersion: "0.1.0",
          props: {
            title: "网格容器示例",
            subtitle: "用两列布局承载基础物料，适合权益、卖点和轻量入口组合。",
            columns: 2,
            backgroundColor: "#ffffff",
            padding: 12,
            marginY: 12,
            gap: 10,
            radius: 12,
            borderColor: "#d1d5db",
            borderWidth: 1,
            shadow: false,
            titleColor: "#111827",
            subtitleColor: "#64748b",
            emptyText: "向网格容器中添加物料",
          },
          children: [
            {
              id: "summer_grid_tag",
              componentName: "BasicTag",
              materialVersion: "0.1.0",
              props: {
                text: "网格标签",
                tone: "accent",
                align: "center",
                textColor: "#0f766e",
                backgroundColor: "rgba(15, 118, 110, 0.1)",
                wrapperBackgroundColor: "#ffffff",
                radius: 999,
                fontSize: 12,
                fontWeight: 800,
                paddingY: 8,
              },
            },
            {
              id: "summer_grid_price",
              componentName: "BasicPrice",
              materialVersion: "0.1.0",
              props: {
                amountText: "299",
                prefix: "¥",
                suffix: "封顶",
                align: "center",
                size: 22,
                color: "#dc2626",
                wrapperBackgroundColor: "#ffffff",
                paddingY: 8,
              },
            },
          ],
        },
        {
          id: "summer_flash_sale",
          componentName: "FlashSaleList",
          materialVersion: "0.1.0",
          props: {
            title: "限时秒杀",
            subtitle: "精选爆品限量抢购",
            badgeText: "秒杀中",
            backgroundColor: "#ffffff",
            items: productItems.slice(0, 2),
          },
          dataBinding: {
            items: "products",
          },
        },
        {
          id: "summer_spacer",
          componentName: "SpacerBlock",
          materialVersion: "0.1.0",
          props: {
            height: 16,
            backgroundColor: "#f3f4f6",
          },
        },
        {
          id: "summer_sticky_action",
          componentName: "StickyActionBar",
          materialVersion: "0.1.0",
          props: {
            title: "限时福利",
            subtitle: "领取优惠后立即逛活动精选",
            primaryText: "立即抢购",
            secondaryText: "领券",
            showSecondary: true,
            sticky: true,
            safeArea: true,
            primaryLinkUrl: "",
            secondaryLinkUrl: "",
            backgroundColor: "#ffffff",
            titleColor: "#111827",
            textColor: "#64748b",
            accentColor: "#111827",
            primaryTextColor: "#ffffff",
            secondaryBackgroundColor: "#ffffff",
            radius: 999,
          },
        },
      ],
      dataSources: [
        {
          id: "ds_products",
          type: "product.byActivity",
          bindTo: "products",
          params: {
            activityId: "summer-campaign-demo",
            limit: 20,
          },
          cache: {
            ttlSeconds: 60,
            scope: "public",
          },
        },
      ],
      actions: [
        {
          id: "summer_basic_form_submit",
          type: "noop",
          params: {
            source: "basic_form_demo",
          },
        },
      ],
      publishMeta: {
        environment: "test",
      },
    }),
  },
  {
    id: "new-user-coupon",
    title: "新人券领取页",
    description: "适合投放拉新、注册礼和首单优惠。",
    category: "拉新转化",
    status: "published",
    tags: ["新人", "优惠券", "首单", "转化"],
    version: "1.0.0",
    schema: createLowcodePageSchema({
      pageId: "new-user-coupon-demo",
      title: "新人专享礼",
      pageType: "promotion",
      targetPlatforms: ["h5"],
      layout: {
        safeArea: true,
        backgroundColor: "#fff7ed",
        maxWidth: 430,
      },
      nodes: [
        {
          id: "new_user_hero",
          componentName: "ActivityHero",
          materialVersion: "0.1.0",
          props: {
            title: "新人专享礼",
            subtitle: "注册即领新人券，首单下单更划算。",
            imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
            backgroundColor: "#ffffff",
            titleColor: "#111827",
            textColor: "#64748b",
            titleSize: 24,
            imageRadius: 8,
            paddingY: 18,
            titleLineHeight: 1.2,
            subtitleLineHeight: 1.6,
          },
        },
        {
          id: "new_user_coupon",
          componentName: "CouponSection",
          materialVersion: "0.1.0",
          props: {
            title: "新人 30 元礼包",
            buttonText: "一键领取",
            backgroundColor: "#ffedd5",
            buttonColor: "#ea580c",
          },
        },
        {
          id: "new_user_notice",
          componentName: "NoticeBar",
          materialVersion: "0.1.0",
          props: {
            showIcon: true,
            iconText: "!",
            label: "规则",
            content: "优惠券领取后 7 天内有效，每个用户限领一次。",
            backgroundColor: "#fff7ed",
            labelBackgroundColor: "rgba(154, 52, 18, 0.1)",
            labelColor: "#9a3412",
            textColor: "#9a3412",
            borderColor: "#fed7aa",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "new_user_rules",
          componentName: "ActivityRuleModal",
          materialVersion: "0.1.0",
          props: {
            title: "新人礼规则",
            summary: "领取前可查看有效期、使用门槛和限制说明。",
            buttonText: "查看规则",
            modalTitle: "新人专享礼规则",
            primaryColor: "#ea580c",
            backgroundColor: "#fff7ed",
            textColor: "#7c2d12",
            rules: [
              { title: "领取限制", content: "每个新用户账号仅可领取一次新人礼包。" },
              { title: "有效时间", content: "优惠券领取后 7 天内有效，逾期自动失效。" },
              { title: "使用说明", content: "优惠券适用范围以商品详情页和结算页展示为准。" },
            ],
          },
        },
        {
          id: "new_user_action",
          componentName: "ActionButton",
          materialVersion: "0.1.0",
          props: {
            text: "去挑选首单好物",
            linkUrl: "",
            backgroundColor: "#ea580c",
            textColor: "#ffffff",
            wrapperBackgroundColor: "#fff7ed",
            radius: 8,
            paddingY: 14,
          },
        },
        {
          id: "new_user_text",
          componentName: "RichTextBlock",
          materialVersion: "0.1.0",
          props: {
            html: "<p><strong>使用说明：</strong>新人券可在指定商品下单时抵扣，具体以结算页展示为准。</p>",
            backgroundColor: "#ffffff",
            textColor: "#7c2d12",
            borderColor: "#fed7aa",
            radius: 10,
            padding: 14,
            fontSize: 14,
            lineHeight: 1.7,
          },
        },
      ],
      publishMeta: {
        environment: "test",
      },
    }),
  },
  {
    id: "product-topic",
    title: "商品专题页",
    description: "适合品类专题、达人推荐和爆品集合。",
    category: "商品运营",
    status: "published",
    tags: ["商品", "专题", "达人", "品类"],
    version: "1.0.0",
    schema: createLowcodePageSchema({
      pageId: "product-topic-demo",
      title: "通勤好物专题",
      pageType: "topic",
      targetPlatforms: ["h5"],
      layout: {
        safeArea: true,
        backgroundColor: "#f3f4f6",
        maxWidth: 430,
      },
      nodes: [
        {
          id: "topic_banner",
          componentName: "ImageBanner",
          materialVersion: "0.1.0",
          props: {
            imageUrl: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?auto=format&fit=crop&w=900&q=80",
            alt: "通勤好物专题",
            radius: 0,
          },
        },
        {
          id: "topic_notice",
          componentName: "NoticeBar",
          materialVersion: "0.1.0",
          props: {
            showIcon: true,
            iconText: "!",
            label: "专题",
            content: "精选通勤穿搭与包履单品，适合工作日快速选购。",
            backgroundColor: "#eff6ff",
            labelBackgroundColor: "rgba(29, 78, 216, 0.1)",
            labelColor: "#1d4ed8",
            textColor: "#1d4ed8",
            borderColor: "#bfdbfe",
            radius: 8,
            paddingY: 10,
          },
        },
        {
          id: "topic_container",
          componentName: "SectionContainer",
          materialVersion: "0.1.0",
          props: {
            title: "编辑精选",
            subtitle: "商品数据可绑定活动、商品 ID 或专题配置。",
            backgroundColor: "#ffffff",
            padding: 14,
            marginY: 12,
            gap: 10,
            radius: 12,
            borderColor: "#d1d5db",
            borderWidth: 1,
            shadow: true,
            titleColor: "#111827",
            subtitleColor: "#64748b",
            emptyText: "向编辑精选中添加物料",
          },
          children: [
            {
              id: "topic_products",
              componentName: "ProductList",
              materialVersion: "0.1.0",
              props: {
                items: productItems,
                backgroundColor: "#ffffff",
                cardBackgroundColor: "#ffffff",
                titleColor: "#111827",
                textColor: "#64748b",
                priceColor: "#dc2626",
                borderColor: "#eef0f3",
                radius: 10,
                imageRadius: 8,
                paddingY: 12,
              },
              dataBinding: {
                items: "products",
              },
            },
          ],
        },
        {
          id: "topic_action",
          componentName: "ActionButton",
          materialVersion: "0.1.0",
          props: {
            text: "查看更多专题商品",
            linkUrl: "",
            backgroundColor: "#111827",
            textColor: "#ffffff",
            wrapperBackgroundColor: "#f3f4f6",
            radius: 8,
            paddingY: 14,
          },
        },
      ],
      dataSources: [
        {
          id: "ds_products",
          type: "product.byActivity",
          bindTo: "products",
          params: {
            activityId: "product-topic-demo",
            limit: 20,
          },
          cache: {
            ttlSeconds: 60,
            scope: "public",
          },
        },
      ],
      publishMeta: {
        environment: "test",
      },
    }),
  },
];
